// Code generated by "stringer -type=SensorStateClass -output stateclass.gen.go -linecomment"; DO NOT EDIT.

package class

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateClassMin-0]
	_ = x[StateMeasurement-1]
	_ = x[StateTotal-2]
	_ = x[StateTotalIncreasing-3]
	_ = x[StateClassMax-4]
}

const _SensorStateClass_name = "measurementtotaltotal_increasing"

var _SensorStateClass_index = [...]uint8{0, 0, 11, 16, 32, 32}

func (i SensorStateClass) String() string {
	if i < 0 || i >= SensorStateClass(len(_SensorStateClass_index)-1) {
		return "SensorStateClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SensorStateClass_name[_SensorStateClass_index[i]:_SensorStateClass_index[i+1]]
}
