version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - godox
    - ireturn
    - lll
    - mnd
    - nlreturn
    - tagalign
    - tagliatelle
    - wsl
  settings:
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G104 # made redundant by errcheck
    lll:
      tab-width: 4
      line-length: 120
    revive:
      enable-all-rules: false
      rules:
        - name: exported
          arguments:
            - disable-checks-on-variables
    varnamelen:
      ignore-names:
        - err
        - wg
        - tt
        - id
        - ok
        - mu
        - fd
        - to
  exclusions:
    rules:
      - linters:
          - lll
        source: "^//go:generate "
      - path: '(.+)_test\.go'
        linters:
          - dupl
          - funlen
          - paralleltest
          - testpackage
          - varnamelen
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/joshuar/go-hass-agent
run:
  timeout: "5m"
  issues-exit-code: 1
  tests: true
  allow-parallel-runners: false
  allow-serial-runners: false
  go: "1.24"
  relative-path-mode: wd
