version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - exhaustive
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - godox
    - ireturn
    - lll
    - mnd
    - nlreturn
    - tagalign
    - tagliatelle
    - wsl
  settings:
    gocyclo:
      min-complexity: 15
    lll:
      tab-width: 4
      line-length: 120
    varnamelen:
      ignore-names:
        - err
        - wg
        - tt
        - id
        - ok
        - mu
        - fd
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - dupl
          - funlen
          - paralleltest
          - testpackage
          - varnamelen
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/joshuar/go-hass-agent

