before:
  hooks:
    - go mod tidy
    # - go generate ./...
    - desktop-file-validate assets/go-hass-agent.desktop
    - fyne-cross linux -icon assets/trayicon/logo-pretty.png -release -app-version {{.Version}}

changelog:
  use: github-native
  sort: asc
  abbrev: 0
  filters:
    exclude:
      - '^docs:'
      - typo

builds:
  - env:
      - CGO_ENABLED=1
    goos:
      - linux
      # - windows
      # - darwin
    goarch:
      - amd64
      # - arm
      # - arm64

# .goreleaser.yaml
archives:
- format: binary

release:
  extra_files:
    - glob: fyne-cross/dist/linux-amd64/go-hass-agent.tar.xz

nfpms:
  - id: go-hass-agent
    package_name: go-hass-agent
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: org.github.joshuar
    homepage: https://github.com/joshuar/go-hass-app
    maintainer: Joshua Rich <joshua.rich@gmail.com>
    description: |-
      A Home Assistant, native app for desktop/laptop devices.
    license: MIT
    formats:
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin
    overrides:
      rpm:
        dependencies:
          - libglvnd-glx
          - libX11
          - libXrandr
          - libXxf86vm
          - libXi
          - libXcursor
          - libXinerama
      deb:
        dependencies:
          - libgl1
          - libxi6
          - libxcursor1
          - libxrandr2
          - libxinerama1
    release: '1'
    section: default
    priority: extra
    meta: false
    contents:
      - src: LICENSE
        dst: /usr/share/licenses/go-hass-agent/LICENSE
      - src: README.md
        dst: /usr/share/doc/go-hass-agent/README.md
      - src: assets/trayicon/logo-pretty.png
        dst: /usr/share/pixmaps/go-hass-agent.png
      - src: assets/go-hass-agent.desktop
        dst: /usr/share/applications/go-hass-agent.desktop
      - src: assets/systemd/go-hass-agent.service
        dst: /usr/lib/systemd/user/go-hass-agent.service
    rpm:
      compression: lzma
    deb:
      lintian_overrides:
        - changelog-file-missing-in-native-package
    archlinux:
      packager: GoReleaser <staff@goreleaser.com>

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
