# nfpm example configuration file
#
# check https://nfpm.goreleaser.com/configuration for detailed usage
#
name: "go-hass-agent"
version: ${APPVERSION}
section: "default"
priority: "extra"
maintainer: Joshua Rich <joshua.rich@gmail.com>
description: |
  A Home Assistant, native app for desktop/laptop devices.
vendor: org.github.joshuar
homepage: https://github.com/joshuar/go-hass-app
license: MIT
arch: ${NFPM_ARCH}
# changelog: CHANGELOG.md
contents:
  - src: dist/go-hass-agent-${NFPM_ARCH}
    dst: /usr/bin/go-hass-agent
    expand: true
  - src: LICENSE
    dst: /usr/share/licenses/go-hass-agent/LICENSE
  - src: README.md
    dst: /usr/share/doc/go-hass-agent/README.md
  - src: internal/agent/ui/assets/go-hass-agent.png
    dst: /usr/share/pixmaps/go-hass-agent.png
  - src: assets/go-hass-agent.desktop
    dst: /usr/share/applications/go-hass-agent.desktop
  - src: init/go-hass-agent.service
    dst: /usr/lib/systemd/user/go-hass-agent.service
overrides:
  rpm:
    depends:
      - libxcursor
      - libXrandr
      - mesa-libGL
      - libXi
      - libXinerama
      - libxxf86vm
      - dbus-x11
  deb:
    depends:
      - libgl1-mesa-dri
      - xorg
      - dbus-x11
  archlinux:
    depends:
      - xorg-server
      - libxcursor
      - libxrandr
      - libxinerama
      - libxi
