# nfpm example configuration file
#
# check https://nfpm.goreleaser.com/configuration for detailed usage
#
name: "go-hass-agent"
version: ${APPVERSION}
section: "default"
priority: "extra"
maintainer: Joshua Rich <joshua.rich@gmail.com>
description: |
  A Home Assistant, native app for desktop/laptop devices.
vendor: org.github.joshuar
homepage: https://github.com/joshuar/go-hass-app
license: MIT
arch: ${GOARCH}
# changelog: CHANGELOG.md
contents:
  - src: dist/go-hass-agent-${GOARCH}
    dst: /usr/bin/go-hass-agent
    expand: true
  - src: LICENSE
    dst: /usr/share/licenses/go-hass-agent/LICENSE
  - src: README.md
    dst: /usr/share/doc/go-hass-agent/README.md
  - src: internal/agent/ui/assets/go-hass-agent.png
    dst: /usr/share/pixmaps/go-hass-agent.png
  - src: assets/go-hass-agent.desktop
    dst: /usr/share/applications/go-hass-agent.desktop
  - src: init/go-hass-agent.service
    dst: /usr/lib/systemd/user/go-hass-agent.service
overrides:
  rpm:
    depends:
      - libglvnd-glx
      - libglvnd
      - libX11
      - libXext
      - libxcb
      - libXau
      - dbus-x11
  deb:
    depends:
      - libgl1 
      - libx11-6 
      - libglx0 
      - libglvnd0 
      - libxcb1 
      - libxau6 
      - libxdmcp6 
      - dbus-x11
  archlinux:
    depends:
      - libglvnd
      - libx11
      - libxrandr
      - libxxf86vm
      - libxi
      - libxcursor
      - libxinerama
      - libxcb
      - libxext
      - libxrender
      - libxfixes
      - libxau
      - libxdmcp
