// Code generated by "stringer -type=batteryProp -output batterySensorProps.go -linecomment"; DO NOT EDIT.

package linux

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[battType-4]
	_ = x[percentage-5]
	_ = x[temperature-6]
	_ = x[voltage-7]
	_ = x[energy-8]
	_ = x[energyRate-9]
	_ = x[battState-10]
	_ = x[nativePath-11]
	_ = x[batteryLevel-12]
	_ = x[model-13]
}

const _batteryProp_name = "Battery TypeBattery LevelBattery TemperatureBattery VoltageBattery EnergyBattery PowerBattery StateBattery PathBattery LevelBattery Model"

var _batteryProp_index = [...]uint8{0, 12, 25, 44, 59, 73, 86, 99, 111, 124, 137}

func (i batteryProp) String() string {
	i -= 4
	if i < 0 || i >= batteryProp(len(_batteryProp_index)-1) {
		return "batteryProp(" + strconv.FormatInt(int64(i+4), 10) + ")"
	}
	return _batteryProp_name[_batteryProp_index[i]:_batteryProp_index[i+1]]
}
