// Code generated by "stringer -type=battChargeState -output batteryStatesStrings.go -linecomment"; DO NOT EDIT.

package linux

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[stateCharging-1]
	_ = x[stateDischarging-2]
	_ = x[stateEmpty-3]
	_ = x[stateFullyCharged-4]
	_ = x[statePendingCharge-5]
	_ = x[statePendingDischarge-6]
}

const _battChargeState_name = "ChargingDischargingEmptyFully ChargedPending ChargePending Discharge"

var _battChargeState_index = [...]uint8{0, 8, 19, 24, 37, 51, 68}

func (i battChargeState) String() string {
	i -= 1
	if i >= battChargeState(len(_battChargeState_index)-1) {
		return "battChargeState(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _battChargeState_name[_battChargeState_index[i]:_battChargeState_index[i+1]]
}
