// Code generated by "stringer -type=BatteryProp -output battery_props_linux.go -trimprefix batt"; DO NOT EDIT.

package linux

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[battType-4]
	_ = x[Percentage-5]
	_ = x[Temperature-6]
	_ = x[Voltage-7]
	_ = x[Energy-8]
	_ = x[EnergyRate-9]
	_ = x[battState-10]
	_ = x[NativePath-11]
	_ = x[BatteryLevel-12]
	_ = x[Model-13]
}

const _BatteryProp_name = "TypePercentageTemperatureVoltageEnergyEnergyRateStateNativePathBatteryLevelModel"

var _BatteryProp_index = [...]uint8{0, 4, 14, 25, 32, 38, 48, 53, 63, 75, 80}

func (i BatteryProp) String() string {
	i -= 4
	if i < 0 || i >= BatteryProp(len(_BatteryProp_index)-1) {
		return "BatteryProp(" + strconv.FormatInt(int64(i+4), 10) + ")"
	}
	return _BatteryProp_name[_BatteryProp_index[i]:_BatteryProp_index[i+1]]
}
