// Code generated by "stringer -type=memoryStat -output mem_stats_linux.go -linecomment"; DO NOT EDIT.

package linux

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[memoryTotal-1]
	_ = x[memoryAvailable-2]
	_ = x[memoryUsed-3]
	_ = x[swapMemoryTotal-4]
	_ = x[swapMemoryUsed-5]
	_ = x[swapMemoryFree-6]
}

const _memoryStat_name = "Memory TotalMemory AvailableMemory UsedSwap Memory TotalSwap Memory UsedSwap Memory Free"

var _memoryStat_index = [...]uint8{0, 12, 28, 39, 56, 72, 88}

func (i memoryStat) String() string {
	i -= 1
	if i < 0 || i >= memoryStat(len(_memoryStat_index)-1) {
		return "memoryStat(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _memoryStat_name[_memoryStat_index[i]:_memoryStat_index[i+1]]
}
