// Code generated by "stringer -type=SensorTypeValue -output sensorTypeStrings.go -linecomment"; DO NOT EDIT.

package linux

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SensorAppActive-1]
	_ = x[SensorAppRunning-2]
	_ = x[SensorBattType-3]
	_ = x[SensorBattPercentage-4]
	_ = x[SensorBattTemp-5]
	_ = x[SensorBattVoltage-6]
	_ = x[SensorBattEnergy-7]
	_ = x[SensorBattEnergyRate-8]
	_ = x[SensorBattState-9]
	_ = x[SensorBattNativePath-10]
	_ = x[SensorBattLevel-11]
	_ = x[SensorBattModel-12]
	_ = x[SensorMemTotal-13]
	_ = x[SensorMemAvail-14]
	_ = x[SensorMemUsed-15]
	_ = x[SensorSwapTotal-16]
	_ = x[SensorSwapUsed-17]
	_ = x[SensorSwapFree-18]
	_ = x[SensorConnectionState-19]
	_ = x[SensorConnectionID-20]
	_ = x[SensorConnectionDevices-21]
	_ = x[SensorConnectionType-22]
	_ = x[SensorConnectionIPv4-23]
	_ = x[SensorConnectionIPv6-24]
	_ = x[SensorAddressIPv4-25]
	_ = x[SensorAddressIPv6-26]
	_ = x[SensorWifiSSID-27]
	_ = x[SensorWifiFrequency-28]
	_ = x[SensorWifiSpeed-29]
	_ = x[SensorWifiStrength-30]
	_ = x[SensorWifiHWAddress-31]
	_ = x[SensorBytesSent-32]
	_ = x[SensorBytesRecv-33]
	_ = x[SensorBytesSentRate-34]
	_ = x[SensorBytesRecvRate-35]
	_ = x[SensorPowerProfile-36]
	_ = x[SensorBoottime-37]
	_ = x[SensorUptime-38]
	_ = x[SensorLoad1-39]
	_ = x[SensorLoad5-40]
	_ = x[SensorLoad15-41]
	_ = x[SensorScreenLock-42]
	_ = x[SensorProblem-43]
	_ = x[SensorKernel-44]
	_ = x[SensorDistribution-45]
	_ = x[SensorVersion-46]
	_ = x[SensorUsers-47]
	_ = x[SensorDeviceTemp-48]
	_ = x[SensorPowerState-49]
}

const _SensorTypeValue_name = "Active AppRunning AppsBattery TypeBattery LevelBattery TemperatureBattery VoltageBattery EnergyBattery PowerBattery StateBattery PathBattery LevelBattery ModelMemory TotalMemory AvailableMemory UsedSwap Memory TotalSwap Memory UsedSwap Memory FreeConnection StateConnection IDConnection DeviceConnection TypeConnection IPv4Connection IPv6IPv4 AddressIPv6 AddressWi-Fi SSIDWi-Fi FrequencyWi-Fi Link SpeedWi-Fi Signal StrengthWi-Fi BSSIDBytes SentBytes ReceivedBytes Sent ThroughputBytes Received ThroughputPower ProfileLast RebootUptimeCPU load average (1 min)CPU load average (5 min)CPU load average (15 min)Screen LockProblemsKernel VersionDistribution NameDistribution VersionCurrent UsersTemperaturePower State"

var _SensorTypeValue_index = [...]uint16{0, 10, 22, 34, 47, 66, 81, 95, 108, 121, 133, 146, 159, 171, 187, 198, 215, 231, 247, 263, 276, 293, 308, 323, 338, 350, 362, 372, 387, 403, 424, 435, 445, 459, 480, 505, 518, 529, 535, 559, 583, 608, 619, 627, 641, 658, 678, 691, 702, 713}

func (i SensorTypeValue) String() string {
	i -= 1
	if i < 0 || i >= SensorTypeValue(len(_SensorTypeValue_index)-1) {
		return "SensorTypeValue(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SensorTypeValue_name[_SensorTypeValue_index[i]:_SensorTypeValue_index[i+1]]
}
