// Code generated by "stringer -type=sensorType -output sensorTypeStrings.go -linecomment"; DO NOT EDIT.

package linux

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[appActive-0]
	_ = x[appRunning-1]
	_ = x[battType-2]
	_ = x[battPercentage-3]
	_ = x[battTemp-4]
	_ = x[battVoltage-5]
	_ = x[battEnergy-6]
	_ = x[battEnergyRate-7]
	_ = x[battState-8]
	_ = x[battNativePath-9]
	_ = x[battLevel-10]
	_ = x[battModel-11]
	_ = x[memTotal-12]
	_ = x[memAvail-13]
	_ = x[memUsed-14]
	_ = x[swapTotal-15]
	_ = x[swapUsed-16]
	_ = x[swapFree-17]
	_ = x[connectionState-18]
	_ = x[connectionID-19]
	_ = x[connectionDevices-20]
	_ = x[connectionType-21]
	_ = x[connectionIPv4-22]
	_ = x[connectionIPv6-23]
	_ = x[addressIPv4-24]
	_ = x[addressIPv6-25]
	_ = x[wifiSSID-26]
	_ = x[wifiFrequency-27]
	_ = x[wifiSpeed-28]
	_ = x[wifiStrength-29]
	_ = x[wifiHWAddress-30]
	_ = x[bytesSent-31]
	_ = x[bytesRecv-32]
	_ = x[powerProfile-33]
	_ = x[boottime-34]
	_ = x[uptime-35]
	_ = x[load1-36]
	_ = x[load5-37]
	_ = x[load15-38]
}

const _sensorType_name = "Active AppRunning AppsBattery TypeBattery LevelBattery TemperatureBattery VoltageBattery EnergyBattery PowerBattery StateBattery PathBattery LevelBattery ModelMemory TotalMemory AvailableMemory UsedSwap Memory TotalSwap Memory UsedSwap Memory FreeConnection StateConnection IDConnection DeviceConnection TypeConnection IPv4Connection IPv6IPv4 AddressIPv6 AddressWi-Fi SSIDWi-Fi FrequencyWi-Fi Link SpeedWi-Fi Signal StrengthWi-Fi BSSIDBytes SentBytes RecievedPower ProfileLast RebootUptimeCPU load average (1 min)CPU load average (5 min)CPU load average (15 min)"

var _sensorType_index = [...]uint16{0, 10, 22, 34, 47, 66, 81, 95, 108, 121, 133, 146, 159, 171, 187, 198, 215, 231, 247, 263, 276, 293, 308, 323, 338, 350, 362, 372, 387, 403, 424, 435, 445, 459, 472, 483, 489, 513, 537, 562}

func (i sensorType) String() string {
	if i < 0 || i >= sensorType(len(_sensorType_index)-1) {
		return "sensorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _sensorType_name[_sensorType_index[i]:_sensorType_index[i+1]]
}
