// Code generated by "stringer -type=timeProp -output timeSensorProps.go -linecomment"; DO NOT EDIT.

package linux

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[boottime-1]
	_ = x[uptime-2]
}

const _timeProp_name = "Last RebootUptime"

var _timeProp_index = [...]uint8{0, 11, 17}

func (i timeProp) String() string {
	i -= 1
	if i < 0 || i >= timeProp(len(_timeProp_index)-1) {
		return "timeProp(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _timeProp_name[_timeProp_index[i]:_timeProp_index[i+1]]
}
