// Code generated by "stringer -type=SensorType -output sensorType_strings.go"; DO NOT EDIT.

package hwmon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-1]
	_ = x[Temp-2]
	_ = x[Fan-3]
	_ = x[Voltage-4]
	_ = x[PWM-5]
	_ = x[Current-6]
	_ = x[Power-7]
	_ = x[Energy-8]
	_ = x[Humidity-9]
	_ = x[Frequency-10]
	_ = x[Alarm-11]
	_ = x[Intrusion-12]
}

const _SensorType_name = "UnknownTempFanVoltagePWMCurrentPowerEnergyHumidityFrequencyAlarmIntrusion"

var _SensorType_index = [...]uint8{0, 7, 11, 14, 21, 24, 31, 36, 42, 50, 59, 64, 73}

func (i SensorType) String() string {
	i -= 1
	if i < 0 || i >= SensorType(len(_SensorType_index)-1) {
		return "SensorType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SensorType_name[_SensorType_index[i]:_SensorType_index[i+1]]
}
