// Code generated by "stringer -type=DeviceClass,BinarySensorDeviceClass -output DeviceClass_generated.go -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeviceClassNone-0]
	_ = x[DeviceClassApparentPower-1]
	_ = x[DeviceClassAqi-2]
	_ = x[DeviceClassAtmosphericPressure-3]
	_ = x[DeviceClassBattery-4]
	_ = x[DeviceClassCarbonDioxide-5]
	_ = x[DeviceClassCarbonMonoxide-6]
	_ = x[DeviceClassCurrent-7]
	_ = x[DeviceClassDataRate-8]
	_ = x[DeviceClassDataSize-9]
	_ = x[DeviceClassDate-10]
	_ = x[DeviceClassDistance-11]
	_ = x[DeviceClassDuration-12]
	_ = x[DeviceClassEnergyStorage-13]
	_ = x[DeviceClassEnum-14]
	_ = x[DeviceClassFrequency-15]
	_ = x[DeviceClassGas-16]
	_ = x[DeviceClassHumidity-17]
	_ = x[DeviceClassIlluminance-18]
	_ = x[DeviceClassIrradiance-19]
	_ = x[DeviceClassMoisture-20]
	_ = x[DeviceClassMonetary-21]
	_ = x[DeviceClassNitrogenDioxide-22]
	_ = x[DeviceClassNitrogenMonoxide-23]
	_ = x[DeviceClassNitrousOxide-24]
	_ = x[DeviceClassOzone-25]
	_ = x[DeviceClassPm1-26]
	_ = x[DeviceClassPm25-27]
	_ = x[DeviceClassPm10-28]
	_ = x[DeviceClassPowerFactor-29]
	_ = x[DeviceClassPower-30]
	_ = x[DeviceClassPrecipitation-31]
	_ = x[DeviceClassPrecipitationIntensity-32]
	_ = x[DeviceClassPressure-33]
	_ = x[DeviceClassReactivePower-34]
	_ = x[DeviceClassSignalStrength-35]
	_ = x[DeviceClassSoundPressure-36]
	_ = x[DeviceClassSpeed-37]
	_ = x[DeviceClassSulphurDioxide-38]
	_ = x[DeviceClassTemperature-39]
	_ = x[DeviceClassTimestamp-40]
	_ = x[DeviceClassVOC-41]
	_ = x[DeviceClassVoltage-42]
	_ = x[DeviceClassVolume-43]
	_ = x[DeviceClassWater-44]
	_ = x[DeviceClassWeight-45]
	_ = x[DeviceClassWindSpeed-46]
}

const _DeviceClass_name = "apparent_poweraqiatmospheric_pressurebatterycarbon_dioxidecarbon_monoxidecurrentdata_ratedata_sizedatedistancedurationenergy_storageenumfrequencygashumidityilluminanceirradiancemoisturemonetarynitrogen_dioxidenitrogen_monoxidenitrous_oxideozonepm1pm25pm10power_factorpowerprecipitationprecipitation_intensitypressurereactive_powersignal_strengthsound_pressurespeedsulphure_dioxidetemperaturetimestampvocvoltagevolumewaterweightwind_speed"

var _DeviceClass_index = [...]uint16{0, 0, 14, 17, 37, 44, 58, 73, 80, 89, 98, 102, 110, 118, 132, 136, 145, 148, 156, 167, 177, 185, 193, 209, 226, 239, 244, 247, 251, 255, 267, 272, 285, 308, 316, 330, 345, 359, 364, 380, 391, 400, 403, 410, 416, 421, 427, 437}

func (i DeviceClass) String() string {
	if i < 0 || i >= DeviceClass(len(_DeviceClass_index)-1) {
		return "DeviceClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DeviceClass_name[_DeviceClass_index[i]:_DeviceClass_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BinarySensorDeviceClassBattery-0]
	_ = x[BinarySensorDeviceClassBatteryCharging-1]
	_ = x[BinarySensorDeviceClassCO-2]
	_ = x[BinarySensorDeviceClassCold-3]
	_ = x[BinarySensorDeviceClassConnectivity-4]
	_ = x[BinarySensorDeviceClassDoor-5]
	_ = x[BinarySensorDeviceClassGarageDoor-6]
	_ = x[BinarySensorDeviceClassGas-7]
	_ = x[BinarySensorDeviceClassHeat-8]
	_ = x[BinarySensorDeviceClassLight-9]
	_ = x[BinarySensorDeviceClassLock-10]
	_ = x[BinarySensorDeviceClassMoisture-11]
	_ = x[BinarySensorDeviceClassMotion-12]
	_ = x[BinarySensorDeviceClassMoving-13]
	_ = x[BinarySensorDeviceClassOccupancy-14]
	_ = x[BinarySensorDeviceClassOpening-15]
	_ = x[BinarySensorDeviceClassPlug-16]
	_ = x[BinarySensorDeviceClassPower-17]
	_ = x[BinarySensorDeviceClassPresence-18]
	_ = x[BinarySensorDeviceClassProblem-19]
	_ = x[BinarySensorDeviceClassRunning-20]
	_ = x[BinarySensorDeviceClassSafety-21]
	_ = x[BinarySensorDeviceClassSmoke-22]
	_ = x[BinarySensorDeviceClassSound-23]
	_ = x[BinarySensorDeviceClassTamper-24]
	_ = x[BinarySensorDeviceClassUpdate-25]
	_ = x[BinarySensorDeviceClassVibration-26]
	_ = x[BinarySensorDeviceClassWindow-27]
}

const _BinarySensorDeviceClass_name = "batterybattery_chargingcarbon_monoxidecoldconnectivitydoorBinarySensorDeviceClassGarageDoorgasheatlightlockmoisturemotionmovingoccupancyopeningplugpowerpresenceproblemrunningsafetysmokesoundtamperupdatevibrationwindow"

var _BinarySensorDeviceClass_index = [...]uint8{0, 7, 23, 38, 42, 54, 58, 91, 94, 98, 103, 107, 115, 121, 127, 136, 143, 147, 152, 160, 167, 174, 180, 185, 190, 196, 202, 211, 217}

func (i BinarySensorDeviceClass) String() string {
	if i < 0 || i >= BinarySensorDeviceClass(len(_BinarySensorDeviceClass_index)-1) {
		return "BinarySensorDeviceClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BinarySensorDeviceClass_name[_BinarySensorDeviceClass_index[i]:_BinarySensorDeviceClass_index[i+1]]
}
