// Code generated by "stringer -type=SensorType -linecomment -output sensortype_generated.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Sensor-0]
	_ = x[BinarySensor-1]
}

const _SensorType_name = "sensorbinary_sensor"

var _SensorType_index = [...]uint8{0, 6, 19}

func (i SensorType) String() string {
	if i < 0 || i >= SensorType(len(_SensorType_index)-1) {
		return "SensorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SensorType_name[_SensorType_index[i]:_SensorType_index[i+1]]
}
