// Code generated by "stringer -type=ioSensor -output ioSensors_generated.go -linecomment"; DO NOT EDIT.

package disk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[diskReads-0]
	_ = x[diskWrites-1]
	_ = x[diskReadRate-2]
	_ = x[diskWriteRate-3]
	_ = x[diskIOInProgress-4]
}

const _ioSensor_name = "Disk ReadsDisk WritesDisk Read RateDisk Write RateDisk IOs In Progress"

var _ioSensor_index = [...]uint8{0, 10, 21, 35, 50, 70}

func (i ioSensor) String() string {
	if i < 0 || i >= ioSensor(len(_ioSensor_index)-1) {
		return "ioSensor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ioSensor_name[_ioSensor_index[i]:_ioSensor_index[i+1]]
}
