// Code generated by "stringer -type=memoryStat -output mem_stats_linux.go"; DO NOT EDIT.

package device

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MemoryTotal-1]
	_ = x[MemoryAvailable-2]
	_ = x[MemoryUsed-3]
	_ = x[SwapMemoryTotal-4]
	_ = x[SwapMemoryUsed-5]
	_ = x[SwapMemoryFree-6]
}

const _memoryStat_name = "MemoryTotalMemoryAvailableMemoryUsedSwapMemoryTotalSwapMemoryUsedSwapMemoryFree"

var _memoryStat_index = [...]uint8{0, 11, 26, 36, 51, 65, 79}

func (i memoryStat) String() string {
	i -= 1
	if i < 0 || i >= memoryStat(len(_memoryStat_index)-1) {
		return "memoryStat(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _memoryStat_name[_memoryStat_index[i]:_memoryStat_index[i+1]]
}
