// Code generated by "stringer -type=memoryStat -output memory_stats_linux.go"; DO NOT EDIT.

package device

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TotalMemory-1]
	_ = x[AvailableMemory-2]
	_ = x[UsedMemory-3]
	_ = x[TotalSwapMemory-4]
	_ = x[UsedSwapMemory-5]
	_ = x[FreeSwapMemory-6]
}

const _memoryStat_name = "TotalMemoryAvailableMemoryUsedMemoryTotalSwapMemoryUsedSwapMemoryFreeSwapMemory"

var _memoryStat_index = [...]uint8{0, 11, 26, 36, 51, 65, 79}

func (i memoryStat) String() string {
	i -= 1
	if i < 0 || i >= memoryStat(len(_memoryStat_index)-1) {
		return "memoryStat(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _memoryStat_name[_memoryStat_index[i]:_memoryStat_index[i+1]]
}
