// Code generated by "stringer -type=networkProp -output network_props_linux.go"; DO NOT EDIT.

package device

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConnectionState-3]
	_ = x[ConnectionID-4]
	_ = x[ConnectionDevices-5]
	_ = x[ConnectionType-6]
	_ = x[ConnectionIPv4-7]
	_ = x[ConnectionIPv6-8]
	_ = x[AddressIPv4-9]
	_ = x[AddressIPv6-10]
	_ = x[WifiSSID-11]
	_ = x[WifiFrequency-12]
	_ = x[WifiSpeed-13]
	_ = x[WifiStrength-14]
}

const _networkProp_name = "ConnectionStateConnectionIDConnectionDevicesConnectionTypeConnectionIPv4ConnectionIPv6AddressIPv4AddressIPv6WifiSSIDWifiFrequencyWifiSpeedWifiStrength"

var _networkProp_index = [...]uint8{0, 15, 27, 44, 58, 72, 86, 97, 108, 116, 129, 138, 150}

func (i networkProp) String() string {
	i -= 3
	if i < 0 || i >= networkProp(len(_networkProp_index)-1) {
		return "networkProp(" + strconv.FormatInt(int64(i+3), 10) + ")"
	}
	return _networkProp_name[_networkProp_index[i]:_networkProp_index[i+1]]
}
