// Code generated by "stringer -type=sensorType -output network_sensortypes_linux.go"; DO NOT EDIT.

package device

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConnectionState-3]
	_ = x[WifiSSID-4]
	_ = x[WifiFrequency-5]
	_ = x[WifiSpeed-6]
	_ = x[WifiStrength-7]
}

const _sensorType_name = "ConnectionStateWifiSSIDWifiFrequencyWifiSpeedWifiStrength"

var _sensorType_index = [...]uint8{0, 15, 23, 36, 45, 57}

func (i sensorType) String() string {
	i -= 3
	if i < 0 || i >= sensorType(len(_sensorType_index)-1) {
		return "sensorType(" + strconv.FormatInt(int64(i+3), 10) + ")"
	}
	return _sensorType_name[_sensorType_index[i]:_sensorType_index[i+1]]
}
