// Code generated by "stringer -type=SensorType -linecomment -output sensorTypeStrings.go"; DO NOT EDIT.

package sensor

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeSensor-1]
	_ = x[TypeBinary-2]
}

const _SensorType_name = "sensorbinary_sensor"

var _SensorType_index = [...]uint8{0, 6, 19}

func (i SensorType) String() string {
	i -= 1
	if i < 0 || i >= SensorType(len(_SensorType_index)-1) {
		return "SensorType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SensorType_name[_SensorType_index[i]:_SensorType_index[i+1]]
}
