// Code generated by "stringer -type=batteryDeviceClass -output batterySensor_string.go"; DO NOT EDIT.

package agent

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[battery-0]
	_ = x[temperature-1]
	_ = x[power-2]
	_ = x[state-3]
}

const _batteryDeviceClass_name = "batterytemperaturepowerstate"

var _batteryDeviceClass_index = [...]uint8{0, 7, 18, 23, 28}

func (i batteryDeviceClass) String() string {
	if i < 0 || i >= batteryDeviceClass(len(_batteryDeviceClass_index)-1) {
		return "batteryDeviceClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _batteryDeviceClass_name[_batteryDeviceClass_index[i]:_batteryDeviceClass_index[i+1]]
}
