// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package agent

import (
	"context"
	"github.com/joshuar/go-hass-agent/internal/hass/sensor"
	"sync"
)

// Ensure, that SensorTrackerMock does implement SensorTracker.
// If this is not the case, regenerate this file with moq.
var _ SensorTracker = &SensorTrackerMock{}

// SensorTrackerMock is a mock implementation of SensorTracker.
//
//	func TestSomethingThatUsesSensorTracker(t *testing.T) {
//
//		// make and configure a mocked SensorTracker
//		mockedSensorTracker := &SensorTrackerMock{
//			GetFunc: func(key string) (sensor.Details, error) {
//				panic("mock out the Get method")
//			},
//			ResetFunc: func()  {
//				panic("mock out the Reset method")
//			},
//			SensorListFunc: func() []string {
//				panic("mock out the SensorList method")
//			},
//			UpdateSensorFunc: func(ctx context.Context, reg sensor.Registry, details sensor.Details) error {
//				panic("mock out the UpdateSensor method")
//			},
//		}
//
//		// use mockedSensorTracker in code that requires SensorTracker
//		// and then make assertions.
//
//	}
type SensorTrackerMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(key string) (sensor.Details, error)

	// ResetFunc mocks the Reset method.
	ResetFunc func()

	// SensorListFunc mocks the SensorList method.
	SensorListFunc func() []string

	// UpdateSensorFunc mocks the UpdateSensor method.
	UpdateSensorFunc func(ctx context.Context, reg sensor.Registry, details sensor.Details) error

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Key is the key argument value.
			Key string
		}
		// Reset holds details about calls to the Reset method.
		Reset []struct {
		}
		// SensorList holds details about calls to the SensorList method.
		SensorList []struct {
		}
		// UpdateSensor holds details about calls to the UpdateSensor method.
		UpdateSensor []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Reg is the reg argument value.
			Reg sensor.Registry
			// Details is the details argument value.
			Details sensor.Details
		}
	}
	lockGet          sync.RWMutex
	lockReset        sync.RWMutex
	lockSensorList   sync.RWMutex
	lockUpdateSensor sync.RWMutex
}

// Get calls GetFunc.
func (mock *SensorTrackerMock) Get(key string) (sensor.Details, error) {
	if mock.GetFunc == nil {
		panic("SensorTrackerMock.GetFunc: method is nil but SensorTracker.Get was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedSensorTracker.GetCalls())
func (mock *SensorTrackerMock) GetCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Reset calls ResetFunc.
func (mock *SensorTrackerMock) Reset() {
	if mock.ResetFunc == nil {
		panic("SensorTrackerMock.ResetFunc: method is nil but SensorTracker.Reset was just called")
	}
	callInfo := struct {
	}{}
	mock.lockReset.Lock()
	mock.calls.Reset = append(mock.calls.Reset, callInfo)
	mock.lockReset.Unlock()
	mock.ResetFunc()
}

// ResetCalls gets all the calls that were made to Reset.
// Check the length with:
//
//	len(mockedSensorTracker.ResetCalls())
func (mock *SensorTrackerMock) ResetCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockReset.RLock()
	calls = mock.calls.Reset
	mock.lockReset.RUnlock()
	return calls
}

// SensorList calls SensorListFunc.
func (mock *SensorTrackerMock) SensorList() []string {
	if mock.SensorListFunc == nil {
		panic("SensorTrackerMock.SensorListFunc: method is nil but SensorTracker.SensorList was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSensorList.Lock()
	mock.calls.SensorList = append(mock.calls.SensorList, callInfo)
	mock.lockSensorList.Unlock()
	return mock.SensorListFunc()
}

// SensorListCalls gets all the calls that were made to SensorList.
// Check the length with:
//
//	len(mockedSensorTracker.SensorListCalls())
func (mock *SensorTrackerMock) SensorListCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSensorList.RLock()
	calls = mock.calls.SensorList
	mock.lockSensorList.RUnlock()
	return calls
}

// UpdateSensor calls UpdateSensorFunc.
func (mock *SensorTrackerMock) UpdateSensor(ctx context.Context, reg sensor.Registry, details sensor.Details) error {
	if mock.UpdateSensorFunc == nil {
		panic("SensorTrackerMock.UpdateSensorFunc: method is nil but SensorTracker.UpdateSensor was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Reg     sensor.Registry
		Details sensor.Details
	}{
		Ctx:     ctx,
		Reg:     reg,
		Details: details,
	}
	mock.lockUpdateSensor.Lock()
	mock.calls.UpdateSensor = append(mock.calls.UpdateSensor, callInfo)
	mock.lockUpdateSensor.Unlock()
	return mock.UpdateSensorFunc(ctx, reg, details)
}

// UpdateSensorCalls gets all the calls that were made to UpdateSensor.
// Check the length with:
//
//	len(mockedSensorTracker.UpdateSensorCalls())
func (mock *SensorTrackerMock) UpdateSensorCalls() []struct {
	Ctx     context.Context
	Reg     sensor.Registry
	Details sensor.Details
} {
	var calls []struct {
		Ctx     context.Context
		Reg     sensor.Registry
		Details sensor.Details
	}
	mock.lockUpdateSensor.RLock()
	calls = mock.calls.UpdateSensor
	mock.lockUpdateSensor.RUnlock()
	return calls
}
