// Code generated by "stringer -type=batterySensor -output battery_generated.go -linecomment"; DO NOT EDIT.

package battery

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[battType-0]
	_ = x[battPercentage-1]
	_ = x[battTemp-2]
	_ = x[battVoltage-3]
	_ = x[battEnergy-4]
	_ = x[battEnergyRate-5]
	_ = x[battState-6]
	_ = x[battNativePath-7]
	_ = x[battLevel-8]
	_ = x[battModel-9]
}

const _batterySensor_name = "Battery TypeBattery LevelBattery TemperatureBattery VoltageBattery EnergyBattery PowerBattery StateBattery PathBattery LevelBattery Model"

var _batterySensor_index = [...]uint8{0, 12, 25, 44, 59, 73, 86, 99, 111, 124, 137}

func (i batterySensor) String() string {
	if i < 0 || i >= batterySensor(len(_batterySensor_index)-1) {
		return "batterySensor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _batterySensor_name[_batterySensor_index[i]:_batterySensor_index[i+1]]
}
