// Code generated by "stringer -type=RequestType -output requestType.go -linecomment"; DO NOT EDIT.

package request

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RequestTypeEncrypted-1]
	_ = x[RequestTypeGetConfig-2]
	_ = x[RequestTypeUpdateLocation-3]
	_ = x[RequestTypeRegisterSensor-4]
	_ = x[RequestTypeUpdateSensorStates-5]
}

const _RequestType_name = "encryptedget_configupdate_locationregister_sensorupdate_sensor_states"

var _RequestType_index = [...]uint8{0, 9, 19, 34, 49, 69}

func (i RequestType) String() string {
	i -= 1
	if i < 0 || i >= RequestType(len(_RequestType_index)-1) {
		return "RequestType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _RequestType_name[_RequestType_index[i]:_RequestType_index[i+1]]
}
