// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"encoding/json"

	externalRef0 "github.com/joshuar/go-hass-agent/models"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
)

// Defines values for RequestType.
const (
	Auth                             RequestType = "auth"
	AuthInvalid                      RequestType = "auth_invalid"
	AuthOk                           RequestType = "auth_ok"
	AuthRequired                     RequestType = "auth_required"
	Encrypted                        RequestType = "encrypted"
	FireEvent                        RequestType = "fire_event"
	GetConfig                        RequestType = "get_config"
	MobileApppushNotificationChannel RequestType = "mobile_app/push_notification_channel"
	Ping                             RequestType = "ping"
	Pong                             RequestType = "pong"
	RegisterSensor                   RequestType = "register_sensor"
	Result                           RequestType = "result"
	UpdateLocation                   RequestType = "update_location"
	UpdateSensorStates               RequestType = "update_sensor_states"
)

// APIError defines an error status returned by the API.
type APIError struct {
	Code    string `json:"code,omitempty,omitzero"`
	Message string `json:"message,omitempty,omitzero"`
}

// ConfigResponse is a response containing Home Assistant configuration details.
type ConfigResponse struct {
	Components []string `json:"components,omitempty,omitzero"`
	ConfigDir  string   `json:"config_dir,omitempty,omitzero"`
	Elevation  int      `json:"elevation,omitempty,omitzero"`

	// Entities is the list sensor entities registered with this app and their status.
	Entities     nullable.Nullable[map[string]map[string]interface{}] `json:"entities,omitempty,omitzero"`
	Latitude     float32                                              `json:"latitude,omitempty,omitzero"`
	LocationName string                                               `json:"location_name,omitempty,omitzero"`
	Longitude    float32                                              `json:"longitude,omitempty,omitzero"`

	// TimeZone is the configured timezone of the Home Assistant instance.
	TimeZone string `json:"time_zone,omitempty,omitzero"`

	// UnitSystem is the current unit systems used by the Home Assistant instance.
	UnitSystem struct {
		Length      string `json:"length,omitempty,omitzero"`
		Mass        string `json:"mass,omitempty,omitzero"`
		Temperature string `json:"temperature,omitempty,omitzero"`
		Volume      string `json:"volume,omitempty,omitzero"`
	} `json:"unit_system,omitempty,omitzero"`

	// Version is the version of Home Assistant.
	Version               string   `json:"version,omitempty,omitzero"`
	WhitelistExternalDirs []string `json:"whitelist_external_dirs,omitempty,omitzero"`
}

// DeviceRegistrationRequest defines the registration details for the device running the agent.
type DeviceRegistrationRequest struct {
	// AppData Contains app data can be used if the app has a supporting component that extends mobile_app functionality.
	AppData map[string]interface{} `json:"app_data,omitempty,omitzero"`

	// AppID is a unique identifier for this app.
	AppID string `json:"app_id"`

	// AppName is the name of the mobile app.
	AppName string `json:"app_name"`

	// AppVersion is the version of the mobile app.
	AppVersion string `json:"app_version"`

	// DeviceID is a unique identifier for this device.
	DeviceID string `json:"device_id"`

	// DeviceName is the name for this device.
	DeviceName string `json:"device_name"`

	// Manufacturer is the manufacturer of the device running the app.
	Manufacturer string `json:"manufacturer"`

	// Model is the model of the device running the app.
	Model string `json:"model"`

	// OsName is the name of the OS running the app.
	OsName string `json:"os_name"`

	// OsVersion is the OS version of the device running the app.
	OsVersion string `json:"os_version"`

	// SupportsEncryption indicates if the app supports encryption.
	SupportsEncryption bool `json:"supports_encryption"`
}

// DeviceRegistrationResponse defines the reponse for a device registration from Home Assistant. Contains URLs to use for connecting to Home Assistant.
type DeviceRegistrationResponse struct {
	// CloudhookURL is the cloudhook URL provided by Home Assistant Cloud. Only will be provided if user is actively subscribed to Nabu Casa.
	CloudhookURL string `json:"cloudhook_url,omitempty,omitzero"`

	// RemoteUIURL is the remote UI URL provided by Home Assistant Cloud. Only will be provided if user is actively subscribed to Nabu Casa.
	RemoteUIURL string `json:"remote_ui_url,omitempty,omitzero"`

	// Secret is the secret to use for encrypted communication. Will only be included if encryption is supported by both the app and the Home Assistant instance. More info.
	Secret string `json:"secret,omitempty,omitzero"`

	// WebhookID is the webhook ID that can be used to send data back.
	WebhookID WebhookID `json:"webhook_id"`
}

// Event defines model for Event.
type Event = externalRef0.Event

// Location defines location details of the device.
type Location = externalRef0.Location

// RequestData defines request data sent through the API.
type RequestData struct {
	// Encrypted indicates the request payload is encrypted.
	Encrypted bool `json:"encrypted,omitzero"`

	// Payload is the request payload.
	Payload *RequestData_Payload `json:"data,omitnil,omitzero"`

	// Retryable indicates whether request for this data can be retried.
	Retryable bool `json:"-"`

	// Type is the type of request.
	Type RequestType `json:"type"`
}

// RequestData_Payload is the request payload.
type RequestData_Payload struct {
	union json.RawMessage
}

// RequestType is the type of request.
type RequestType string

// ResponseData defines response data received through the API.
type ResponseData struct {
	union json.RawMessage
}

// ResponseStatus contains response specific details returned from the Home Assistant API.
type ResponseStatus struct {
	// Error contains API specific error details for a failed request.
	Error nullable.Nullable[APIError] `json:"error,omitempty,omitzero"`

	// IsDisabled is returned for sensor entity requests and indicates whether the sensor entity has been disabled in Home Assistant.
	IsDisabled nullable.Nullable[bool] `json:"is_disabled,omitempty,omitzero"`

	// IsSuccess is returned to indicate that the success status of the request.
	IsSuccess nullable.Nullable[bool] `json:"success,omitempty,omitzero"`
}

// SensorRegistration defines a sensor to be registered with Home Assistant.
type SensorRegistration = externalRef0.SensorRegistration

// SensorRegistrationResponse contains details on sensor registration status.
type SensorRegistrationResponse struct {
	Error APIError `json:"error,omitempty,omitzero"`

	// Success indicates if the sensor registration was successful.
	Success bool `json:"success,omitempty,omitzero"`
}

// SensorState defines the current state of a sensor.
type SensorState = externalRef0.SensorState

// SensorStateResponse contains a map of response status for each sensor state sent.
type SensorStateResponse map[string]ResponseStatus

// WebhookID is the webhook ID that can be used to send data back.
type WebhookID = string

// AsLocation returns the union data inside the RequestData_Payload as a Location
func (t RequestData_Payload) AsLocation() (Location, error) {
	var body Location
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLocation overwrites any union data inside the RequestData_Payload as the provided Location
func (t *RequestData_Payload) FromLocation(v Location) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLocation performs a merge with any union data inside the RequestData_Payload, using the provided Location
func (t *RequestData_Payload) MergeLocation(v Location) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSensorState returns the union data inside the RequestData_Payload as a SensorState
func (t RequestData_Payload) AsSensorState() (SensorState, error) {
	var body SensorState
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSensorState overwrites any union data inside the RequestData_Payload as the provided SensorState
func (t *RequestData_Payload) FromSensorState(v SensorState) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSensorState performs a merge with any union data inside the RequestData_Payload, using the provided SensorState
func (t *RequestData_Payload) MergeSensorState(v SensorState) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSensorRegistration returns the union data inside the RequestData_Payload as a SensorRegistration
func (t RequestData_Payload) AsSensorRegistration() (SensorRegistration, error) {
	var body SensorRegistration
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSensorRegistration overwrites any union data inside the RequestData_Payload as the provided SensorRegistration
func (t *RequestData_Payload) FromSensorRegistration(v SensorRegistration) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSensorRegistration performs a merge with any union data inside the RequestData_Payload, using the provided SensorRegistration
func (t *RequestData_Payload) MergeSensorRegistration(v SensorRegistration) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsEvent returns the union data inside the RequestData_Payload as a Event
func (t RequestData_Payload) AsEvent() (Event, error) {
	var body Event
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEvent overwrites any union data inside the RequestData_Payload as the provided Event
func (t *RequestData_Payload) FromEvent(v Event) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEvent performs a merge with any union data inside the RequestData_Payload, using the provided Event
func (t *RequestData_Payload) MergeEvent(v Event) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDeviceRegistrationRequest returns the union data inside the RequestData_Payload as a DeviceRegistrationRequest
func (t RequestData_Payload) AsDeviceRegistrationRequest() (DeviceRegistrationRequest, error) {
	var body DeviceRegistrationRequest
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeviceRegistrationRequest overwrites any union data inside the RequestData_Payload as the provided DeviceRegistrationRequest
func (t *RequestData_Payload) FromDeviceRegistrationRequest(v DeviceRegistrationRequest) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeviceRegistrationRequest performs a merge with any union data inside the RequestData_Payload, using the provided DeviceRegistrationRequest
func (t *RequestData_Payload) MergeDeviceRegistrationRequest(v DeviceRegistrationRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RequestData_Payload) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RequestData_Payload) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsSensorStateResponse returns the union data inside the ResponseData as a SensorStateResponse
func (t ResponseData) AsSensorStateResponse() (SensorStateResponse, error) {
	var body SensorStateResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSensorStateResponse overwrites any union data inside the ResponseData as the provided SensorStateResponse
func (t *ResponseData) FromSensorStateResponse(v SensorStateResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSensorStateResponse performs a merge with any union data inside the ResponseData, using the provided SensorStateResponse
func (t *ResponseData) MergeSensorStateResponse(v SensorStateResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSensorRegistrationResponse returns the union data inside the ResponseData as a SensorRegistrationResponse
func (t ResponseData) AsSensorRegistrationResponse() (SensorRegistrationResponse, error) {
	var body SensorRegistrationResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSensorRegistrationResponse overwrites any union data inside the ResponseData as the provided SensorRegistrationResponse
func (t *ResponseData) FromSensorRegistrationResponse(v SensorRegistrationResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSensorRegistrationResponse performs a merge with any union data inside the ResponseData, using the provided SensorRegistrationResponse
func (t *ResponseData) MergeSensorRegistrationResponse(v SensorRegistrationResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsConfigResponse returns the union data inside the ResponseData as a ConfigResponse
func (t ResponseData) AsConfigResponse() (ConfigResponse, error) {
	var body ConfigResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromConfigResponse overwrites any union data inside the ResponseData as the provided ConfigResponse
func (t *ResponseData) FromConfigResponse(v ConfigResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeConfigResponse performs a merge with any union data inside the ResponseData, using the provided ConfigResponse
func (t *ResponseData) MergeConfigResponse(v ConfigResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsResponseStatus returns the union data inside the ResponseData as a ResponseStatus
func (t ResponseData) AsResponseStatus() (ResponseStatus, error) {
	var body ResponseStatus
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromResponseStatus overwrites any union data inside the ResponseData as the provided ResponseStatus
func (t *ResponseData) FromResponseStatus(v ResponseStatus) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeResponseStatus performs a merge with any union data inside the ResponseData, using the provided ResponseStatus
func (t *ResponseData) MergeResponseStatus(v ResponseStatus) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDeviceRegistrationResponse returns the union data inside the ResponseData as a DeviceRegistrationResponse
func (t ResponseData) AsDeviceRegistrationResponse() (DeviceRegistrationResponse, error) {
	var body DeviceRegistrationResponse
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDeviceRegistrationResponse overwrites any union data inside the ResponseData as the provided DeviceRegistrationResponse
func (t *ResponseData) FromDeviceRegistrationResponse(v DeviceRegistrationResponse) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDeviceRegistrationResponse performs a merge with any union data inside the ResponseData, using the provided DeviceRegistrationResponse
func (t *ResponseData) MergeDeviceRegistrationResponse(v DeviceRegistrationResponse) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ResponseData) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ResponseData) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
