// Code generated by "stringer -type=netStatsType -output stats.gen.go -linecomment"; DO NOT EDIT.

package net

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[statBytesSent-0]
	_ = x[statBytesRecv-1]
	_ = x[bytesSentRate-2]
	_ = x[bytesRecvRate-3]
}

const _netStatsType_name = "Bytes SentBytes ReceivedBytes Sent ThroughputBytes Received Throughput"

var _netStatsType_index = [...]uint8{0, 10, 24, 45, 70}

func (i netStatsType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_netStatsType_index)-1 {
		return "netStatsType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _netStatsType_name[_netStatsType_index[idx]:_netStatsType_index[idx+1]]
}
