# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/refs/heads/main/schemas/v3.0/schema.yaml

# Copyright 2025 Joshua Rich <joshua.rich@gmail.com>.
# SPDX-License-Identifier: MIT

openapi: "3.0.3"
info:
  version: 1.0.0
  title: Home Assistant websocket API
  description: Schema and models for using the Home Assistant websocket API.
paths: {}
components:
  schemas:
    WebSocketRequest:
      description: >
        is a request made over the Home Assistant websocket connection.
      type: object
      required:
        - type
      properties:
        type:
          $ref: 'rest.yaml#/components/schemas/RequestType'
        webhook_id:
          $ref: 'rest.yaml#/components/schemas/WebhookID'
        access_token:
          type: string
        id:
          type: string
        support_confirm:
          type: string
    WebSocketResponse:
      description: >
        is a response from Home Assistant over the websocket connection.
      type: object
      required:
        - type
      properties:
        type:
          $ref: 'rest.yaml#/components/schemas/RequestType'

