// Code generated by "stringer -type=dbusType -output busType_strings.go"; DO NOT EDIT.

package dbusx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SessionBus-0]
	_ = x[SystemBus-1]
}

const _dbusType_name = "SessionBusSystemBus"

var _dbusType_index = [...]uint8{0, 10, 19}

func (i dbusType) String() string {
	if i < 0 || i >= dbusType(len(_dbusType_index)-1) {
		return "dbusType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _dbusType_name[_dbusType_index[i]:_dbusType_index[i+1]]
}
