// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de": &dictionary{index: deIndex, data: deData},
		"en": &dictionary{index: enIndex, data: enData},
		"fr": &dictionary{index: frIndex, data: frData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"About":                           1,
	"App Registration":                7,
	"App Settings":                    5,
	"App Version: %s":                 9,
	"App Version: %s\tHA Version: %s": 10,
	"Auto-discovered Servers":         13,
	"Fyne Settings":                   4,
	"MQTT Password":                   20,
	"MQTT Server":                     17,
	"MQTT Topic":                      18,
	"MQTT User":                       19,
	"Manual Server Entry":             15,
	"Ok":                              11,
	"Quit":                            0,
	"Report Issue":                    2,
	"Request Feature":                 3,
	"Sensors":                         6,
	"To register the agent, please enter the relevant details for your Home Assistant\nserver (if not auto-detected) and long-lived access token.": 8,
	"Token":              12,
	"Use Custom Server?": 14,
	"Use MQTT?":          16,
}

var deIndex = []uint32{ // 22 elements
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000,
} // Size: 112 bytes

const deData string = ""

var enIndex = []uint32{ // 22 elements
	0x00000000, 0x00000005, 0x0000000b, 0x00000018,
	0x00000028, 0x00000036, 0x00000043, 0x0000004b,
	0x0000005c, 0x000000e8, 0x000000fb, 0x00000120,
	0x00000123, 0x00000129, 0x00000141, 0x00000154,
	0x00000168, 0x00000172, 0x0000017e, 0x00000189,
	0x00000193, 0x000001a1,
} // Size: 112 bytes

const enData string = "" + // Size: 417 bytes
	"\x02Quit\x02About\x02Report Issue\x02Request Feature\x02Fyne Settings" +
	"\x02App Settings\x02Sensors\x02App Registration\x02To register the agent" +
	", please enter the relevant details for your Home Assistant\x0aserver (i" +
	"f not auto-detected) and long-lived access token.\x02App Version: %[1]s" +
	"\x02App Version: %[1]s\x09HA Version: %[2]s\x02Ok\x02Token\x02Auto-disco" +
	"vered Servers\x02Use Custom Server?\x02Manual Server Entry\x02Use MQTT?" +
	"\x02MQTT Server\x02MQTT Topic\x02MQTT User\x02MQTT Password"

var frIndex = []uint32{ // 22 elements
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000, 0x00000000,
} // Size: 112 bytes

const frData string = ""

// Total table size 753 bytes (0KiB); checksum: E0533B52
