// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%s: %s":                          13,
	"App Registration":                0,
	"App Version: %s\tHA Version: %s": 7,
	"As an initial step, this app will need to log into your Home Assistant server and register itself.\nPlease enter the relevant details for your Home Assistant server url/port and a long-lived access token.": 6,
	"Auto-discovered Servers": 2,
	"Manual Server Entry":     4,
	"Ok":                      8,
	"Report Issue":            9,
	"Request Feature":         10,
	"Sensors":                 12,
	"Settings":                11,
	"Token":                   1,
	"Use Custom Server?":      3,
	"Use TLS?":                5,
}

var enIndex = []uint32{ // 15 elements
	0x00000000, 0x00000011, 0x00000017, 0x0000002f,
	0x00000042, 0x00000056, 0x0000005f, 0x0000012b,
	0x00000150, 0x00000153, 0x00000160, 0x00000170,
	0x00000179, 0x00000181, 0x0000018e,
} // Size: 84 bytes

const enData string = "" + // Size: 398 bytes
	"\x02App Registration\x02Token\x02Auto-discovered Servers\x02Use Custom S" +
	"erver?\x02Manual Server Entry\x02Use TLS?\x02As an initial step, this ap" +
	"p will need to log into your Home Assistant server and register itself." +
	"\x0aPlease enter the relevant details for your Home Assistant server url" +
	"/port and a long-lived access token.\x02App Version: %[1]s\x09HA Version" +
	": %[2]s\x02Ok\x02Report Issue\x02Request Feature\x02Settings\x02Sensors" +
	"\x02%[1]s: %[2]s"

	// Total table size 482 bytes (0KiB); checksum: 8085B27B
