// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"About %s":         7,
	"App Registration": 0,
	"App Version: %s":  8,
	"As an initial step, this app will need to log into your Home Assistant server and register itself.\nPlease enter the relevant details for your Home Assistant server url/port and a long-lived access token.": 6,
	"Auto-discovered Servers": 2,
	"Manual Server Entry":     4,
	"Token":                   1,
	"Use Custom Server?":      3,
	"Use TLS?":                5,
}

var enIndex = []uint32{ // 10 elements
	0x00000000, 0x00000011, 0x00000017, 0x0000002f,
	0x00000042, 0x00000056, 0x0000005f, 0x0000012b,
	0x00000137, 0x0000014a,
} // Size: 64 bytes

const enData string = "" + // Size: 330 bytes
	"\x02App Registration\x02Token\x02Auto-discovered Servers\x02Use Custom S" +
	"erver?\x02Manual Server Entry\x02Use TLS?\x02As an initial step, this ap" +
	"p will need to log into your Home Assistant server and register itself." +
	"\x0aPlease enter the relevant details for your Home Assistant server url" +
	"/port and a long-lived access token.\x02About %[1]s\x02App Version: %[1]" +
	"s"

	// Total table size 394 bytes (0KiB); checksum: F6B7E254
