// Code generated by "stringer -type=SensorStateClass -output sensorStateClassStrings.go -trimprefix State"; DO NOT EDIT.

package hass

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateMeasurement-1]
	_ = x[StateTotal-2]
	_ = x[StateTotalIncreasing-3]
}

const _SensorStateClass_name = "MeasurementTotalTotalIncreasing"

var _SensorStateClass_index = [...]uint8{0, 11, 16, 31}

func (i SensorStateClass) String() string {
	i -= 1
	if i < 0 || i >= SensorStateClass(len(_SensorStateClass_index)-1) {
		return "SensorStateClass(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SensorStateClass_name[_SensorStateClass_index[i]:_SensorStateClass_index[i+1]]
}
