// Code generated by "stringer -type=SensorDeviceClass -output sensorDeviceClassStrings.go -trimprefix Sensor"; DO NOT EDIT.

package hass

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Apparent_power-1]
	_ = x[Aqi-2]
	_ = x[Atmospheric_pressure-3]
	_ = x[SensorBattery-4]
	_ = x[Carbon_dioxide-5]
	_ = x[Carbon_monoxide-6]
	_ = x[Current-7]
	_ = x[Data_rate-8]
	_ = x[Data_size-9]
	_ = x[Date-10]
	_ = x[Distance-11]
	_ = x[Duration-12]
	_ = x[Energy-13]
	_ = x[Enum-14]
	_ = x[Frequency-15]
	_ = x[Gas-16]
	_ = x[Humidity-17]
	_ = x[Illuminance-18]
	_ = x[Irradiance-19]
	_ = x[Moisture-20]
	_ = x[Monetary-21]
	_ = x[Nitrogen_dioxide-22]
	_ = x[Nitrogen_monoxide-23]
	_ = x[Nitrous_oxide-24]
	_ = x[Ozone-25]
	_ = x[Pm1-26]
	_ = x[Pm25-27]
	_ = x[Pm10-28]
	_ = x[Power_factor-29]
	_ = x[SensorPower-30]
	_ = x[Precipitation-31]
	_ = x[Precipitation_intensity-32]
	_ = x[Pressure-33]
	_ = x[Reactive_power-34]
	_ = x[Signal_strength-35]
	_ = x[Sound_pressure-36]
	_ = x[Speed-37]
	_ = x[Sulphur_dioxide-38]
	_ = x[SensorTemperature-39]
	_ = x[Timestamp-40]
	_ = x[Volatile_organic_compounds-41]
	_ = x[Voltage-42]
	_ = x[Volume-43]
	_ = x[Water-44]
	_ = x[Weight-45]
	_ = x[Wind_speed-46]
}

const _SensorDeviceClass_name = "Apparent_powerAqiAtmospheric_pressureBatteryCarbon_dioxideCarbon_monoxideCurrentData_rateData_sizeDateDistanceDurationEnergyEnumFrequencyGasHumidityIlluminanceIrradianceMoistureMonetaryNitrogen_dioxideNitrogen_monoxideNitrous_oxideOzonePm1Pm25Pm10Power_factorPowerPrecipitationPrecipitation_intensityPressureReactive_powerSignal_strengthSound_pressureSpeedSulphur_dioxideTemperatureTimestampVolatile_organic_compoundsVoltageVolumeWaterWeightWind_speed"

var _SensorDeviceClass_index = [...]uint16{0, 14, 17, 37, 44, 58, 73, 80, 89, 98, 102, 110, 118, 124, 128, 137, 140, 148, 159, 169, 177, 185, 201, 218, 231, 236, 239, 243, 247, 259, 264, 277, 300, 308, 322, 337, 351, 356, 371, 382, 391, 417, 424, 430, 435, 441, 451}

func (i SensorDeviceClass) String() string {
	i -= 1
	if i < 0 || i >= SensorDeviceClass(len(_SensorDeviceClass_index)-1) {
		return "SensorDeviceClass(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _SensorDeviceClass_name[_SensorDeviceClass_index[i]:_SensorDeviceClass_index[i+1]]
}
