// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package ui

import (
	"github.com/joshuar/go-hass-agent/internal/tracker"
	"sync"
)

// Ensure, that SensorTrackerMock does implement SensorTracker.
// If this is not the case, regenerate this file with moq.
var _ SensorTracker = &SensorTrackerMock{}

// SensorTrackerMock is a mock implementation of SensorTracker.
//
//	func TestSomethingThatUsesSensorTracker(t *testing.T) {
//
//		// make and configure a mocked SensorTracker
//		mockedSensorTracker := &SensorTrackerMock{
//			GetFunc: func(key string) (tracker.Sensor, error) {
//				panic("mock out the Get method")
//			},
//			SensorListFunc: func() []string {
//				panic("mock out the SensorList method")
//			},
//		}
//
//		// use mockedSensorTracker in code that requires SensorTracker
//		// and then make assertions.
//
//	}
type SensorTrackerMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(key string) (tracker.Sensor, error)

	// SensorListFunc mocks the SensorList method.
	SensorListFunc func() []string

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Key is the key argument value.
			Key string
		}
		// SensorList holds details about calls to the SensorList method.
		SensorList []struct {
		}
	}
	lockGet        sync.RWMutex
	lockSensorList sync.RWMutex
}

// Get calls GetFunc.
func (mock *SensorTrackerMock) Get(key string) (tracker.Sensor, error) {
	if mock.GetFunc == nil {
		panic("SensorTrackerMock.GetFunc: method is nil but SensorTracker.Get was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedSensorTracker.GetCalls())
func (mock *SensorTrackerMock) GetCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// SensorList calls SensorListFunc.
func (mock *SensorTrackerMock) SensorList() []string {
	if mock.SensorListFunc == nil {
		panic("SensorTrackerMock.SensorListFunc: method is nil but SensorTracker.SensorList was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSensorList.Lock()
	mock.calls.SensorList = append(mock.calls.SensorList, callInfo)
	mock.lockSensorList.Unlock()
	return mock.SensorListFunc()
}

// SensorListCalls gets all the calls that were made to SensorList.
// Check the length with:
//
//	len(mockedSensorTracker.SensorListCalls())
func (mock *SensorTrackerMock) SensorListCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSensorList.RLock()
	calls = mock.calls.SensorList
	mock.lockSensorList.RUnlock()
	return calls
}
