name: Permissions Advisor

permissions:
  actions: read

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'The name of the workflow file to analyze'
        required: true
        type: string
      count:
        description: 'How many last runs to analyze'
        required: false
        type: number
        default: 10

jobs:
  advisor:
    runs-on: ubuntu-22.04
    steps:
    - uses: GitHubSecurityLab/actions-permissions/advisor@e83639073897b68de235d81a783b2221cc13def7 # v1
      with:
        name: ${{ inputs.name }}
        count: ${{ inputs.count }}
