name: Analysis

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  nilaway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install build dependencies
        id: install_packages
        run: >
            sudo apt-get update && sudo apt-get -y install
            desktop-file-utils gcc
            libgl1-mesa-dev xserver-xorg-dev 
            libxcursor-dev libxrandr-dev
            libxinerama-dev libxi-dev
            libgl1-mesa-dev libxxf86vm-dev 
            > ${RUNNER_TEMP}/dpkg.log
        env:
          DEBIAN_FRONTEND: noninteractive
      - name: Set up Go
        id: setup_go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22'        
      - name: Install Go dependencies
        id: install_go_deps
        run: |
          go install golang.org/x/tools/cmd/stringer@latest
          go install golang.org/x/text/cmd/gotext@latest
          go install github.com/matryer/moq@latest
      - name: Run go generate
        id: go_generate
        run: go generate -v ./...
      - name: Nil panic checks
        uses: qbaware/nilaway-action@v0
        with:
          package-to-scan: .          
