on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release_please
        name: Run release please
        with:
          release-type: go
          token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Setup Go
      #   id: setup_go
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: '1.19.x'
      # - name: Install Go dependencies
      #   id: install_go_deps
      #   run: |
      #     go install golang.org/x/tools/cmd/stringer@latest
      #     go install github.com/abice/go-enum@latest
      #     go install github.com/fyne-io/fyne-cross@latest
      #     go install golang.org/x/text/cmd/gotext@latest
      # - name: Install dependencies
      #   id: install_linux_deps
      #   run: sudo apt-get install -y desktop-file-utils gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev
      # - if: ${{ steps.release_please.outputs.releases_created }}
      #   name: Run goreleaser
      #   uses: goreleaser/goreleaser-action@v2
      #   with:
      #     version: latest
      #     args: release --rm-dist
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}