// Code generated by "stringer -type=gpuMemStatID -output gpuStats.gen.go -linecomment"; DO NOT EDIT.

package mem

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[memVRamTotal-0]
	_ = x[memGTTTotal-1]
	_ = x[memVRamUsed-2]
	_ = x[memGTTUsed-3]
}

const _gpuMemStatID_name = "GPU VRam Memory TotalGPU GTT Memory TotalGPU VRam Memory UsedGPU GTT Memory Used"

var _gpuMemStatID_index = [...]uint8{0, 21, 41, 61, 80}

func (i gpuMemStatID) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_gpuMemStatID_index)-1 {
		return "gpuMemStatID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _gpuMemStatID_name[_gpuMemStatID_index[idx]:_gpuMemStatID_index[idx+1]]
}
